version: '3'
services:
    mysql:
        container_name: dev-mysql
        hostname: mysql
        image: mysql:8.0.25
        restart: unless-stopped
        tty: true
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            TZ: Europe/Moscow
            MYSQL_ROOT_PASSWORD: root
    nginx:
        container_name: dev-nginx
        hostname: nginx
        image: nginx:1.21.0-alpine
        restart: unless-stopped
        tty: true
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./www:/var/app
            - ./logs:/var/log/nginx
            - ./nginx/enabled:/etc/nginx/conf.d
            - ./nginx/snippets:/nginx/snippets
            - phpmyadmin_data:/var/www/html/:ro
        environment:
            TZ: Europe/Moscow
    php:
        container_name: dev-php
        build:
            context: ./php/.
        image: dev/php:8.0-fpm-alpine
        hostname: php
        restart: unless-stopped
        tty: true
        volumes:
            - ./www:/var/app
            - ./logs:/usr/local/php-logs
        working_dir: /var/app
        environment:
            TZ: Europe/Moscow
            COMPOSER_MEMORY_LIMIT: -1
    redis:
        container_name: dev-redis
        hostname: redis
        image: redis:6.2.4-alpine
        restart: unless-stopped
        tty: true
        command: redis-server --appendonly yes
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - ./db/redis:/data
        environment:
            TZ: Europe/Moscow
    pma:
        container_name: dev-pma
        hostname: pma
        image: phpmyadmin:5.1.1-fpm-alpine
        restart: unless-stopped
        tty: true
        volumes:
            - phpmyadmin_data:/var/www/html/
        environment:
            TZ: Europe/Moscow
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

volumes:
    phpmyadmin_data:
